app/app/settings.py
app/notebooks/Requete en base.ipynb
app/requirements.txt
docker-compose.yml

Ajout des Jupyter Notebooks dans le projet, ce qui permet de faire tourner les notebooks en ayant accès au code du projet et à la database.
Pour lancer le serveur Jupyter, il faut lancer la commande `python manage.py shell_plus --notebook` depuis le container web.

Ajout de Jpuyter Notebook au projet

---

app/api_alpha/__init__.py
app/batid/tests/__init__.py

Le contenu de ces __init__.py permet d'appeler les tests depuis unittest directement sans paser par `manage.py test`.
Ce qui permet en particulier de lancer les tests directement depuis VS Code et même de les debugger :nail_care: 
Ca m'a donné du mal mais je pense que ça sera pratique à l'avenir !

Permettre l'execution des tests en dehors de manage.py

---

app/api_alpha/views.py
app/app/settings.py
app/requirements.txt

J'utilise le package drf-api-tracking ce qui permet assez facilement de tracker l'usage de notre API.
Les statistiques sont stockées en base et sont accessibles facilement depuis le panel admin du site, ce qui est pratique !

Ajout de statistiques d'usage sur l'API

---

app/api_alpha/tests/test_buildings.py
app/api_alpha/views.py
app/batid/list_bdg.py
app/batid/management/commands/sandbox.py
app/batid/models.py
app/batid/services/bdg_status.py
app/batid/services/search_bdg.py
app/notebooks/Prototype score pour rapprochement.ipynb

Pour des raisons de perfs, on sépare l'algo de rapprochement des simples endpoints de listing de bâtiment. Cette PR contient le nouveau mécanisme pour les endpoints de listing et de consultation d'un bâtiment.

Detacher l'api batiment de BuildingSearch

---

app/api_alpha/pagination.py
app/api_alpha/views.py

On doit retirer le compte total de résultats (et donc de pages) sur l'API bâtiments. Le compte total est bien trop gourmand.

Pagination sans "count" pour nb total de pages sur API bdg

---

app/api_alpha/tests/test_buildings.py
app/batid/list_bdg.py
app/batid/services/search_bdg.py
app/batid/tests/test_public_bdg_queryset.py

Retrait des paramètres de recherche qui sont maintenant dans le queryset renvoyé par public_bdg_queryset et filter_bdg_querysert.
Adaptation des tests en conséquence.

Nettoyage du BuildingSearch

---

.env.worker.example
app/app/settings.py
app/app/urls.py
app/batid/views.py
app/requirements.txt
docker-compose.prod.yml
docker-compose.yml

[Flower](https://flower.readthedocs.io/en/latest/) est l'outil officiellement [recommandé](https://docs.celeryq.dev/en/stable/userguide/monitoring.html#flower-real-time-celery-web-monitor) pour monitorer Celery.
Cette PR l'installe et créée une page `/flower` qui nécessite pour être visitée d'être loggé sur le site en tant qu'admin.
J'utilise pour cela le package django-reverse, qui permet de rediriger toutes les requetes qui sont faites sur /flower dans le container web vers le container dédié flower.
Sources utiles:
* https://medium.com/@muhammad-azeem-akhter/integrating-flower-with-celery-in-django-project-using-docker-5ba37a8d7dee
* https://stackoverflow.com/a/75329234/1892308

Ajout de Flower 🌼 pour monitorer Celery 

---

app/batid/services/rnb_id.py

L'alphabet disponible pour la génération des identifiants a été indiqué ici : https://github.com/fab-geocommuns/BatID/issues/24#issue-1597255114
L'alphabet qui tournait en production contenait les L et les U alors que ça ne devrait pas être le cas (cf. lien ci-dessus).

Modification de l'alphabet de génération des identifiants

---

app/api_alpha/tests/test_buildings.py
app/api_alpha/views.py
app/batid/list_bdg.py
app/batid/management/commands/sandbox.py
app/batid/services/building.py
app/batid/tasks.py

Nous avons constaté que le endpoint de listing des bâtiment était lent, en particulier sur les requêtes filtrant les bâtiment par ville. Par exemple :
```
https://rnb-api.beta.gouv.fr/api/alpha/buildings/?insee_code=33422
```
Cela était dû à deux raisons qui se combinaient : 
- une requête très mal écrite avec notamment une double jointure vers une même table
- un système de pagination (LIMIT et OFFSET) s'accomodant très mal de filtre géographique sur une table de 40M d'enregistrements
Pour remédier à cela, nous avons : 
- nettoyé la requête initiale
- modifié le système de pagination pour adopter une pagination par curseur (cf [documentation de Django Rest Framework à ce sujet](https://www.django-rest-framework.org/api-guide/pagination/#cursorpagination)).

Améliore la vitesse du endpoint de listing de bâtiments

---

docker-compose.prod.yml
docker-compose.staging.yml

Après avoir constaté régulièrement que les performances de la carto publique pouvaient être mauvaises, nous avons investigué et il s'avère que gunicorn n'était configuré que pour gérer une seule requête à la fois. 
Le passage à 6 workers et 6 threads augmente drastiquement les performances et règle le problème de la carto.

Gunicorn performance configuration

---

app/api_alpha/tests/test_log.py
app/api_alpha/urls.py
app/api_alpha/views.py

Suite à la mise en place d'Uptime Robot, nous avons faussé nos stats de consultation de nos endpoints.
On ajoute une simple règle faisant que les urls ayant un paramètre from=monitoring ne sont pas prises en comptes dans les logs.

Eviter enregistrement des appels à l'url quand issus du monitoring

---

docker-compose.staging.yml

Je passe la concurrency de celery à 4 sur staging et je passe le mode en thread, car nos taches sont plus IO bound que CPU bound (c'est la base qui fait le gros du travail, plus que le worker)

allow worker concurrency

---

app/batid/management/commands/import_bdnb_dpt.py
app/batid/management/commands/import_bdtopo_dpt.py
app/batid/management/commands/import_france.py
app/batid/services/imports/building_import_history.py
app/batid/services/imports/import_bdnb7.py
app/batid/services/imports/import_bdtopo.py
app/batid/tasks.py
app/batid/tests/test_import_bdnb.py
app/batid/tests/test_import_france.py

J'avais pas bien expliqué le but de ce champ :  permettre de savoir que plusieurs imports viennent de la même commande (typiquement un import france qui génère plusieurs imports départementaux). Je remets le code comme avant et je rajoute des tests sur cet aspect là.

le retour de bulk_launch_uuid

---

app/batid/services/candidate.py

Sur la base d'import, la requete passe à ~50ms en rajoutant le inspected_at dans le order by.

Tentative d'accélération

---

app/api_alpha/serializers.py
app/api_alpha/tests/test_bdg_guess.py
app/batid/services/guess_bdg.py

L'utilisation d'un score relatif n'était pas facile à manipuler. On repasse à un score absolu. Aussi, on affiche les sous-scores pour plus facilement comprendre comment est construit ce score.

Score absolu et sous score dans rapprochement

---

app/batid/services/s3_backup/backup_task.py
app/batid/tasks.py
app/batid/tests/test_s3_backups.py
docker-compose.yml

Je pense que les messages d'erreur que nous recevons lors des backups scaleway ne viennent pas de la prod, mais d'une autre instance de l'app qui tourne _quelque part_. Ca n'a pas l'air d'être les instances de staging ou sandbox. Peut-être que ça vient de mon ordi, j'avais un service beat qui tournait dessus, je ne sais pas s'il est capable de lancer des tasks alors que l'ordi est en veille ?
En tout cas je supprime le service celery_beat du docker compose local et je rajoute la task id dans le message mattermost lorsque le backup a échoué, ce qui nous permettra d'identifier à coup sûr qui a envoyé la notification d'erreur si on continue d'en recevoir.

Pas de celery beat en local

---

app/batid/services/data_gouv_publication.py
app/batid/tests/test_data_gouv_publication.py

Scaleway n'a pas le même nombre de "parts" autorisé lors d'un upload sur son S3 que AWS (1,000 versus 10,000)
Notre lib `boto3` qui sert d'interface avec S3 utilise le défaut de AWS, et les upload qui dépassent 1000 parts échouent.
Le comportement est configurable.
https://stackoverflow.com/questions/53257823/how-to-set-expected-size-option-in-boto3-clients3-upload-fileobj

Adaptation pour upload de gros fichiers sur S3

---

app/batid/management/commands/sandbox.py
app/requirements.txt

On ne semble plus s'en servir.
lié à #331 , car encore mieux que mettre à jour, il y a supprimer !

Suppression de shapely

---

docker-compose.import.yml
docker-compose.prod.yml
docker-compose.staging.yml

Nous n'avons plus besoin de deux workers par installation. On les supprime de prod, import et staging.

Suppression des services worker_2

---

docker-compose.yml

La propriété `version` est optionnelle, purement informative.
cf : https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-optional
Le nom du projet `name` permet de préfixer le nom des conteneurs et des images.
cf : https://docs.docker.com/compose/compose-file/04-version-and-name/#name-top-level-element

Suppression de version (deprecated), ajout nom projet

---

.github/workflows/tests.yml

La CI de test utilisait encore la commande `docker-compose` qui est dépréciée au profit de `docker compose`.

Remplacement de docker-compose par docker compose.

---

app/api_alpha/views.py
app/batid/tests/test_tiles.py

Ajout d'une contrainte de zoom min (>= 16) dans l'API pour la génération des tuiles

Ajout d'un min_zoom dans l'API 

---

app/batid/management/commands/publish_opendata.py
docker-compose.prod.yml

Permettre de lancer la génération de l'opendata en commençant à un département précis.

Add start-at option to publish_opendata command

---

app/api_alpha/serializers.py
app/batid/admin.py

Le champs email était déjà présent dans le model `Contribution`.
J'ajoute le champ au serializer et l'affiche dans le backoffice.

Ajout des emails dans les signalements

---

app/batid/services/imports/import_bdtopo.py
app/batid/tasks.py
app/batid/tests/test_bdtopo.py

J'ai voulu relancer l'import de la BD Topo suite au blocage de RabbitMQ hier mais, pas de chance, on se retrouve dans un créneau où la date du dernier millésime vient de passer (2024-06-15) mais celui-ci n'est pas encore publié (il devrait l'être dans qq semaines).
J'ajoute un paramètre de date à la tâche permettant de lancer un import complet de la BD Topo :
```shell
docker exec -ti web celery call batid.tasks.queue_full_bdtopo_import --kwargs='{"before":"2024-06-01"}'
```

Choix de date pour l'import de la BD Topo

---

.gitignore

Comme indiqué dans la documentation d'installation (https://rnb-fr.gitbook.io/documentation/repository-rnb-coeur/installation), il faut dupliquer des fichiers .env pour se créer une configuration en local.
Le fichier `.env.nginx-encrypt.dev` est le seul à ne pas être ignoré dans Git.

Ajout du fichier .env.nginx-encrypt.dev dans le gitignore

---

app/api_alpha/tests/test_ads.py
app/api_alpha/validators.py

Il est possible de créer un ADS avec un RNB ID et une géométrie.
Étant donné que le RNB ID est déjà lié à une géométrie de source sûre, sauvegarder une autre géométrie en plus dans l'ADS est inutile et source d'erreur.

Empêcher la création d'un ADS avec un RNB ID et une géométrie

---

app/batid/services/administrative_areas.py
app/batid/services/imports/import_bdtopo.py
app/batid/services/source.py
app/batid/tasks.py
app/batid/tests/test_import_bdtopo.py

Le disque de prod se remplit rapidement avec le nouvel import de la BD Topo. Avec cette PR, on supprime les dossiers contenant la BD Topo d'un département après l'import de ceux-ci.
Aussi, on ajoute deux paramètres permettant de faire un import uniquement entre tel et tel département.

Suppression des dossier BD Topo d'un département après import

---

app/batid/services/source.py

Le chemin vers le répertoire à vider n'était pas bon

Fix : suppression des fichiers décompressé

---

common-services.yml

Je vais migrer notre base de prod vers Postgres 15.
La [release](https://www.postgresql.org/docs/release/15.0/) note mentionne notamment "Performance improvements, particularly for in-memory and on-disk sorting" ce qui pourra nous intéresser.
Je vous laisse voir comment vous gérez le passage de Postgres 14 vers 15 en local chez vous. De mon côté ma base locale était quasiment vide, je l'ai donc supprimée, puis j'en ai recréé une nouvelle en lui appliquant les migrations de Django (`python manage.py migrate`).

Mise à jour postgres / postgis version dans docker compose

---

app/api_alpha/serializers.py
app/api_alpha/urls.py
app/api_alpha/utils/drf_spectacular_extension.py
app/api_alpha/views.py
app/app/settings.py
app/batid/apps.py

Afin de document nos APIs via la génération d'une documentation "code first", cette PR ajoute les annotations `@extend_schema` de DRF Spectacular afin de compléter les informations manquantes issues du Gitbook (https://rnb-fr.gitbook.io/documentation).

Ajout de l'annotation @extend_schema de DRF Spectacular pour documenter nos APIs

---

.github/workflows/tests.yml
app/Dockerfile
app/pyproject.toml

Mise à jour de la version Python utilisée.
Les changelogs sont [ici](https://docs.python.org/3/whatsnew/3.11.html#what-s-new-in-python-3-11) et i[ci](https://docs.python.org/3/whatsnew/3.12.html). J'ai regardé les section sur les deprecation et les removed features, j'ai rien vu qui m'a sauté aux yeux.
Les tests passent et le projet tourne bien en local chez moi.

Update python to version 3.12.4

---

app/batid/admin.py
app/batid/services/ads.py
app/batid/views.py

On a besoin de régulièrement exporter les ADS pour en faire des stats. On ajoute ce lien à la liste des ADS dans le backoffice de Django.

Lien export des ADS

---

app/batid/management/commands/sandbox.py
app/batid/services/contributions.py

Utilisation de `dictfetchall` pour récupération des données au bon format.

Hotfix : export contributions

---

app/batid/management/commands/sandbox.py
app/batid/services/candidate.py
app/batid/tests/test_inspector.py

Nous avons des candidats qui ne peuvent être correctement inspectés du fait d'un bug présent dans GEOS 3.11. Le problème est décrit dans ctte question [GIS Stackexchange](https://gis.stackexchange.com/questions/484691/topologyexception-side-location-conflict-while-intersects-on-valid-polygons?noredirect=1#comment790715_484691).
Quand le candidat souffre de bug, nous interceptons l'exception et indiquons que ce candidat a été refusé et attachons la raison `topology_exception`.
Il s'agira de reprendre ces candidats une fois que nous serons passé à une version de GEOS sans bug (la 3.12).

Gestion des candidats souffrant du bug GEOS

---

common-services.yml
nginx/Dockerfile

Notre config docker avait mal vieilli, et il était devenu impossible de remettre sur pieds un serveur pour notre application (suite à un [breaking change](https://github.com/nginx-proxy/acme-companion/releases/tag/v2.4.0) de la version 2.4.0 de nginxproxy/acme-companion, et au fait que nous tirions d'un cote le container nginx avec une version fixée et ancienne, mais acme-companion en `latest`.
⚠️ : NE PAS MERGER, CA RISQUE DE CASSER LA PROD QUI NE PEUT PLUS BUILDER DE NOUVELLES IMAGES

Update nginx docker containers

---

app/batid/services/data_fix/remove_light_buildings.py

Pour pouvoir relancer le job quand il plante, il ne faut pas supprimer le folder qui contient les résultats déja sortis, sinon on ne va jamais s'en sortir. Les serveurs de l'IGN sont régulièrement hors service et les téléchargements de la BDTOPO échouent.

Batiment légers : petit fix

---

app/batid/services/data_fix/remove_light_buildings.py

On a des crashs sur certains départements à cause d'une erreur sur le calcul de la surface.
"lwgeom_area_spher(oid) returned area < 0.0"
Je pense que ces cas sont rares, je vais sauter les buildings concernés par le problème et noter leur rnb_id dans un fichier à part, quitte à y revenir par la suite.

Doublons : fix

---

app/batid/models.py
app/batid/tests/test_models.py

Je n'ai pas envie qu'on puisse `soft_delete` un batiment qui est deja inactif, ni de le mettre à jour.

Ne pas autoriser d'opérations sur des batiments inactifs

---

app/api_alpha/permissions.py
app/api_alpha/tests/test_ads.py

J'ai modifié la vérification des permissions pour rendre les endpoints de consultation et de listing d'ADS publics.
Les tests sont adaptés en conséquence.

Endpoints de lecture des ADS publics

---

app/api_alpha/tests/test_ads.py
app/api_alpha/urls.py
app/api_alpha/views.py

Les bloqueurs de pubs nous posent des problèmes pour l'affichage des ADS sur notre carte. Ils bloquent les appels aux urls contenant ADS et empêchent donc qu'on puisse obtenir les détails d'une ADS via des `https://rnb-api.beta.gouv.fr/api/alpha/**ads**/[file_number]/`
Pour parer à cela, on créé des urls miroirs des endpoints ADS et des urls des tuiles vectorielles des ADS. Elle contiennent `permis` à la place d'`ads`.
Les autres urls (celles contenant `/ads/`) continuent d'être nos urls "officielles".
Les urls `/permis/` n'ont pas vocation à être diffusées ou documentées.

Nouveaux endpoints pour ADS

---

app/api_alpha/tests/test_views.py
app/api_alpha/validators.py
app/api_alpha/views.py

La [PR471](https://github.com/fab-geocommuns/RNB-coeur/pull/471) combinée au grand nettoyage des doublons/légers a ralenti le endpoint de réception des signalements (environ 9 secondes pour que le serveur réponde).
En bref, à la réception d'une contribution, on vérifie que l'identifiant concerné est actif. Le problème est que la requête telle qu'elle était écrite déclenchait un IndexScan sur le critère `is_active=False` puis passait en revue les 5M de lignes pour trouver le bon identifiant RNB.
J'ai changé la vérification pour que l'on récupère d'abord le bâtiment via rnb_id puis qu'on vérifie son `is_active`.
La version plus propre aurait probablement été de faire cette vérification en une opération. Il aurait fallu créer un index combiné `rnb_id` et `is_active` mais j'ai estimé que …

Réparation endpoint signalement

---

app/api_alpha/tests/test_views.py
app/api_alpha/views.py
app/batid/services/stats.py
app/batid/tests/test_stats.py

J'ai modifié la façon dont est obtenu le nombre de bâtiments actifs depuis `/api_alpha/stats/`.
On passe maitenant par le chiffre mis en cache (cf [PR485](https://github.com/fab-geocommuns/RNB-coeur/pull/485))

Lire bdg_count depuis fichier de cache

---

app/batid/management/commands/dpt_count.py
app/batid/management/commands/import_dpt.py
app/batid/services/administrative_areas.py
app/batid/services/imports/import_dpt.py
app/batid/tests/test_administrativeareas.py

Suite à une remarque d'un utilisateur de notre export data gouv, j'ai constaté que certains COM étaient absentes (975, 977, 978) de notre liste de départements (ce ne sont pas des départements à proprement parler mais on les qualifie ainsi par facilité).
J'ai nettoyé quelques fonctions liées aux limites administratives.
Une fois la PR mergée, il faudra procéder manuellement à l'import (commande `import_dpt`) des trois COM manquantes en prod ainsi que des villes (commande `import_cities_dpt`).

Ajout des COM manquantes

---

app/batid/views.py

Authoriser les dashboards Metabase publiques à s'afficher sans être authentifié à Django afin de pouvoir les exporter dans Notion par exemple voir sur notre site plus tard.
L'objectif est d'authoriser certaines URLs:
- Page HTML des dashboards publiques
- Ressources nécessaires (scripts, fonts...)
- API publiques
Pour information, les dashboards sont privés par défaut.

Authoriser les dashboards Metabase publiques

---

app/api_alpha/tests/test_buildings.py
app/batid/list_bdg.py

Détecté par [Sentry](https://sentry.incubateur.net/organizations/betagouv/issues/140968/?project=148&query=&referrer=project-issue-stream) 
On passe de 22 queries en 572ms 
à 3 queries en 172ms (en local)
Avec une ligne de code.
yay!

Suppression d'un problème de N+1 queries

---

app/batid/services/guess_bdg.py

Cette fois ci c'est sur le endpoint de guess, on passe de 43 requêtes à 3 et ça divise le temps de la requête par deux environ.
Avant (1145ms) :
Après (504ms) :

Encore des N+1 (endpoint guess) => 🗑️ 

---

app/api_alpha/serializers.py
app/api_alpha/tests/test_buildings.py
app/api_alpha/views.py

on devait toujours écrire un commentaire pour écrire dans le RNB, on a eu comme retour que c'était contraignant et souvent inutile.

API : rendre les commentaires optionnels 

---

app/batid/services/imports/import_bdtopo.py

La création des 300+ tâches liées à l'import de la BD Topo ont fait crasher le serveur. J'ai pu reproduire le bug en local. Dès que je tentais de lancer plus 5 départements, la fonction de création des tâches n'aboutissait pas. La création des 300 tâches a très probablement fait saturer la mémoire du serveur et aurait conduit au crash.
Le souci vient de l'utilisation de plusieurs `group` de tâches Celery. Pour chaque département, on créait une tâche pour le téléchargement de la donnée, une tâche pour l'import puis un groupe de tâches pour l'inspection. Il semble qu'on ne [puisse pas chaîner plusieurs groups](https://stackoverflow.com/questions/15123772/celery-chaining-groups-and-subtasks-out-of-order-execution) dans Celery.
Pour corriger, je déclenche un seul groupe d'inspection à la fin …

Import BD Topo : fix

---

app/batid/services/imports/import_plots.py
app/batid/tasks.py
app/batid/tests/test_import_plots.py

Le 30/01 l'import automatique du cadastre a crashé : 
```bash
Traceback (most recent call last):
File "/python_venv/app-9TtSrW0h-py3.12/lib/python3.12/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost raise WorkerLostError(billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 4.
```
J'ai pu reproduire cette erreur en local en réduisant la mémoire disponible pour le worker. Dans le docker-compose.yml, sous `worker`:
```yml
deploy:
resources:
limits:
memory: 2024M
```
L'erreur venait de la création en mémoire d'un CSV contenant toutes les parcelles à importer. En découpant cette partie en batch de 100000 lignes on divise par deux la consommation de mémoire.

Consommation de mémoire plus basse lors de l'import du cadastre

---

.gitignore
app/batid/services/candidate.py
app/batid/tests/test_inspector.py

Lors de l'import de la bd topo on a trouvé assez facilement des cas de candidats ayant un polygone qui devrait être attaché à un bâtiment rnb n'ayant qu'un point.
Ce lien n'était pas créé car le point du bâtiment était légèrement à côté du polygone du candidat. L'inspecteur demandait une intersection pour envisager la mise à jour.
Cela posait problème car on ratait des mises à jour mais surtout cela donnait lieu à des créations de bâtiments. On se retrouvait donc avec des cas où deux bâtiments RNB (un point et un polygones) se retrouvaient côte à côté.
Pour corriger cela, on change l'inspecteur pour qu'il tente d'associer les bâtiments se trouvant dans un rayon de 3 mètres et on change les règle d'appariement pour les couples point <> polygone.

Meilleure prise en compte des bâtiments point lors de l'inspection

---

docker-compose.yml

Pas sûr que ce soit utile, vu que je viens de setup mon environnement je peux avoir raté quelque chose, mais j'ai l'impression que ça m'étais nécessaire pour remote-debug avec VSCode

Add remote debugging by default in dev docker-compose

---

app/poetry.lock

`poetry show -o`pour voir la liste des dépendances à mettre à jour
puis 
`poetry update` pour mettre à jour ce qui peut l'être en respectant les contraintes du pyproject.toml

Mises à jour de dépendances Python

---

app/batid/management/commands/sandbox.py
app/batid/services/imports/import_bdtopo.py
app/batid/tasks.py

Le téléchargement de la BD Topo pour Wallis et Futuna n'a pas marché. Sur le site de l'IGN, je vois quela BD Topo n'est pas disponible pour Wallis et Futuna ainsi que pour la Polynésie française.

Correction import Wallis et Futuna

---

app/batid/tests/test_email.py

On avait un test qui pour fonctionner supposait qu'on set une variable d'environnement.
Il est possible de mocker cette variable pour rendre le test indépendant de sa valeur, tout en continuant bien à tester que le code va correctement chercher la valeur de cette variable.

Rendre un test indépendant de la valeur d'une variable d'env

---

.github/workflows/deploy_production.yml

J'ajoute le déploiement sur sandbox depuis les github actions.
Les clés sont les mêmes, c'est l'IP du serveur qui change.
J'ai rajouté un secret dans le repo pour l'IP du serveur de sandbox

Synchroniser le déploiement sur la prod et sur sandbox

---

app/batid/admin.py

Mini PR : on affiche les BuildingImport dans le BO de django pour un suivi un peu plus facile des différents imports.

Afficher les BuildingImport dans le backoffice

---

app/app/settings.py
app/batid/tasks.py

Cette très grosse PR modifie en profondeur la configuration de celery beat.
Plus sérieusement, c'est notre meilleure piste pour expliquer le fait que les tâches qui devaient avoir lieu dans la nuit du 14 au 15 avril n'ont pas eu lieu du tout.
Il n'est pas certain que ce soit la solution mais de toute façon c'est une erreur.

Fix dans la conf de celery beat

---

app/batid/admin.py
app/batid/tests/test_admin.py

Maintenant que l'email est obligatoire, il faut rajouter le champ au formulaire de création d'un User.

Réparer le formulaire de création de user dans Django admin

---

app/poetry.lock

Une série d'updates qui sont dans les limites de nos versions constraints listées dans pyproject.toml.
Les tests passent, j'ai rien vu qui me paraisse trop dangereux.
- Updating rpds-py (0.23.1 -> 0.24.0)
- Updating typing-extensions (4.12.2 -> 4.13.2)
- Updating jsonschema-specifications (2024.10.1 -> 2025.4.1)
- Updating pyzmq (26.3.0 -> 26.4.0)
- Updating soupsieve (2.6 -> 2.7)
- Updating beautifulsoup4 (4.13.3 -> 4.13.4)
- Updating packaging (24.2 -> 25.0)
- Updating prompt-toolkit (3.0.50 -> 3.0.51)
- Updating debugpy (1.8.13 -> 1.8.14)
- Updating h11 (0.14.0 -> 0.16.0)
- Updating ipython (9.0.2 -> 9.1.0)
- Updating urllib3 (2.3.0 -> 2.4.0)
- Updating botocore (1.37.19 -> 1.37.38)
- Updating httpcore (1.0.7 -> 1.0.9)
- Updating json5 (0.10.0 -> 0.12.0)
- Updating tzdata (2025.1 -> …

Update Python packages

---

app/batid/services/email.py

Je change l'url de changement de mot passe qui indiquée dans l'email de renouvellement. Pour que cela corresponde à l'adresse utilsiée par le site

Changement lein vers nouveau mot de passe

---

app/api_alpha/tests/test_summerchallenge_api.py
app/api_alpha/views.py

Si on interrogeait le endpoint de ranking individuel avec un email (ce que le front fait quand on se log avec son email et qui est un autre problème méritant d'être réglé) alors on obtenait une 404.

Utiliser l'email dans le user ranking

---

app/api_alpha/serializers.py
app/api_alpha/tests/buildings/test_creation.py
app/api_alpha/tests/test_buildings.py

On a eu le cas d'envoi d'une shape vide (ex : `POLYGON EMPTY`) via la carte. Cela a fait crashé ce bâtiment (500 quand le consulte via l'API).
Ce patch empêche l'envoi de shape vide

Empecher les shapes vides

---

app/api_alpha/serializers/building_history.py
app/api_alpha/tests/test_history.py
app/batid/services/bdg_history.py

En plus de `shape`, on ajoute `point` dans les attributs retournés par le endpoint d'historique. Cela permettra de générer plus facilement les liens vers le site de la BAN et le site Remonter le temps de l'IGN

Point dans endpoint d'historique

---

common-services.yml

et Postgis 3.5, pour être en ligne avec les dernières versions disponibles sur Scaleway.
Pour connaitre les versions en commandes SQL :
```
SELECT PostGIS_Version();
select version();
```

MAJ vers Postgres 16

---

app/Dockerfile

De ce que j'ai compris :
- Lorsque pipx installe poetry il utilise par défaut une certaine version de Python.
- pour savoir laquelle, on peut faire `pipx install --help` et on obtient (entre autre) `The default python executable used to install a package is /usr/bin/python3`
- On peut donc faire `/usr/bin/python3 --version` et on voit que pipx utilise par défaut Python3.11
```
#12 [worker base  5/12] RUN /usr/bin/python3 --version
#12 0.146 Python 3.11.2
```
- poetry se retrouve alors installé dans un environnement en Python 3.11 qui n'est pas compatible avec les requirements listés dans pyproject.toml
- Je peux vérifier vers quelle version pointe la commande `python3` :
```
#11 [worker base  4/11] RUN which python3
#11 0.205 /usr/local/bin/python3
#11 DONE 0.2s
#12 [web base  5/11] RUN …
```

Fix du docker build

---

app/batid/views.py

Pour mettre à jour notre page stats, j'aimerais mettre directement des questions metabase.

Autoriser les urls publiques de questions metabase

---

.env.worker.example
app/Dockerfile
app/app/settings.py
app/batid/services/data_gouv_publication.py
app/batid/services/source.py
app/batid/tests/data_fix/test_remove_light_buildings.py
common-services.yml
docker-compose.prod.yml
docker-compose.sandbox.yml
docker-compose.staging.yml
docker-compose.test.yml
docker-compose.yml
nginx/Dockerfile

- Rajout d'un `cap_drop` explicite sur les containers de l'app
- Utiliser un utilisateur non-root pour `web` et `worker`
- Changement applicatif pour simplifier cela : utiliser un répertoire temporaire plutôt qu'un mounted volume
- ~J'ai split cette tâche à part pour Nginx : c'est plus compliqué et à voir si on souhaite garder ça v.s. un LB devant~
- EDIT: Vu avec @am-beta, le worker process en lui même n'est pas root, donc il semble overkill de changer le user de nginx-proxy pour le moment

Strengthen Docker containers
