- app/batid/models.py
Je me posais la question en lisant le code de ce que signifiait ce champ, j'en profite pour rajouter un petit commentaire dans le modèle de données.
> Ajout d'un commentaire pour les "light" buildings

- app/batid/management/commands/sandbox.py
- app/batid/services/guess_bdg.py
Le score d'un batiment devient :
score_absolu / total des score_absolu
> changer la formule de calcul de score pour la borner entre 0 et 1.

- .github/workflows/tests.yml
Celle la je vais la merger direct parce que ça va nous embeter pour toutes les PR en cours.
> Jouer les test sur la branche the_import

- app/batid/services/imports/import_bdnb_2023_01.py
Une suggestion faite sous forme de proposition dans un commentaire github que je croyais passée en meme temps que la PR #275
> Mini oubli suite à PR pour import nouvelle bdnb

- app/batid/services/imports/import_bdnb_2023_01.py
il manquait l'argument dans la fonction
> Correction import BDNB (bulk_launch_uuid)

- app/batid/services/vector_tiles.py
Condition du mauvais côté de la parenthèse
> Réparation express des tuiles

- app/batid/tests/test_tiles.py
Pour éviter de casser la prod à l'avenir comme je viens de le faire...
> Ajout d'un test pour le endpoint des tuiles vectorielles

- app/api_alpha/tests/test_views.py
- app/api_alpha/urls.py
- app/api_alpha/views.py
Ce endpoint va être appelé par le front pour récupérer des stats dynamiquement.
> Création d'un endpoint pour les données de la page stats

- app/batid/services/populate_addresses_id_field.py
Je ne fais des commit que toutes les 10000 lignes
> MAJ query update des addresses meilleure perf

- app/batid/services/populate_addresses_id_field.py
pour relancer le script qui a planté en cours de route, j'utilise une méthode plus rapide pour savoir d'où on repart.
> better way to compute min_id

- app/batid/services/data_gouv_publication.py
En faisant une modif dans la PR précédente #393 j'ai fait une erreur : le code essaye de supprimer deux fois le répertoire de travail.
> Fix publication data.gouv

- app/api_alpha/tests/test_ads.py
- app/api_alpha/urls.py
- app/api_alpha/views.py
Afin de créer des tokens pour les ADS, nous avons besoin d'une nouvelle API qui permet de le faire par lot.
> Ajout d'une API de création de tokens ADS

- app/batid/admin.py
- app/batid/models.py
Permet d'accéder aux ADS ainsi qu'a leur détail depuis l'interface Admin de Django
> Ajout des ADS dans l'interface Admin

- app/notebooks/outils/Creation utilisateurs ADS via CSV.ipynb
Ca script à été utilisé le 27/06/2024 afin de créer les 85 premiers utilisateurs ADS.
D'autres utilisations sont à prévoir donc je crée un notebook afin de le partager.
> Ajout d'un notebook de création d'utilisateurs ADS à partir d'un fichier CSV

- app/batid/admin.py
- app/batid/management/commands/sandbox.py
- app/batid/services/ads.py
- app/batid/services/contributions.py
- app/batid/templates/admin/batid/contribution/change_list.html
- app/batid/views.py
On ajoute un lien d'export des contributions au backoffice. Cela sera utile au reste de l'équipe.
> Export des signalements

- app/notebooks/rapprochements/Operat/rapprochement.ipynb
- app/poetry.lock
- app/pyproject.toml
Le notebook qui a permis de faire le rapprochement Operat dont les résultats sont [ici](https://www.notion.so/referentielnationaldesbatiments/Faire-rapprochement-OPERAT-7960725a479e4015b39d281498027e29?pvs=4#0c09d675bc7544a18a4b93e489695804).
J'ai dû retoucher un peu les dépendances de dev pour que ça fonctionne, j'avais oublié quelques packages lors du passage à Poetry.
> Notebook rapprochement Operat

- app/notebooks/rapprochements/Grenoble/rapprochement.ipynb
Le notebook qui m'a permis de faire le rapprochement de Grenoble dont j'ai envoyé les résultats le 7 aout par mail à Virginie
> Rapprochement Grenoble

- app/api_alpha/views.py
Modification de l'API de récupération du score des contributions afin de terminer le jeu de l'été au 3 septembre 2024 au soir.
> Ajout de la date de fin du jeu de l'été

- app/api_alpha/views.py
> Retouches présentation doc du endpoint de diff

- .github/workflows/deploy.yml
le chemin a changé sur le serveur
> Mise à jour script de déploiement

- app/api_alpha/views.py
J'en profite pour faire une modif de quelque chose qui déplait à pre-commit et qui bloque le formattage automatique.
> Petite correction dans la doc

- app/app/settings.py
- app/batid/management/commands/publish_opendata.py
- app/batid/services/data_gouv_publication.py
- app/batid/tasks.py
J'ai créé un nouvelle tâche récurrente. Chaque samedi, la publication sur data gouv se fait pour les 104 départements et pour le national.
> Publication automatique sur data.gouv.fr

- .gitignore
- app/batid/management/commands/sandbox.py
- app/batid/services/guess_bdg_new.py
- app/notebooks/rapprochements/lyon-echantillon/Rapprochement échantillon.ipynb
Le notebook (et une légère retouche de la classe `Guesser`) pour le rapprochemet des 500k+ lignes d'Accès Libre.
> Rapprochement Accès Libre

- app/batid/services/data_fix/fill_empty_event_origin.py
- app/batid/tasks.py
- app/batid/tests/data_fix/test_fix_missing_event_origin.py
En laissant la possibilité de lancer plusieurs tâches en //
> Rendre la réparation de la base plus rapide

- app/batid/views.py
Changement d'une URL pour authoriser les URLs de type:
- /metabase/app/fonts
- /metabase/app/icons
- etc...
> Authoriser les dashboards Metabase publiques

- app/api_alpha/tests/test_buildings.py
- app/batid/services/closest_bdg.py
- app/batid/services/guess_bdg.py
Sur le endpoint de closest cette fois.
> Encore une N+1

- app/api_alpha/views.py
> Correction d'un import

- app/app/dbrouters.py
- app/batid/tests/data_fix/test_fix_missing_event_origin.py
> Réactivation d'une protection d'écriture dans la base

- app/api_alpha/serializers.py
- app/api_alpha/tests/test_buildings.py
- app/api_alpha/views.py
- app/batid/models.py
J'ajoute la possibilité de modifier la shape à la méthode PATCH.
> API : permettre la mise à jour de la shape d'un bâtiment

- readme.md
This is what I used to seed the database.
I only added the standard Django command to create the superuser, even though I had to create another user, because I think depending on the chosen reference point and how the database evolves the requirements will probably change.
> Update readme with instructions to import buildings and addresses around a point

- app/api_alpha/tests/test_views.py
- app/api_alpha/views.py
...qui m'avait échappé, actuellement une partie du fichier sort avec des `,`et l'autre avec des `tab`
> Endpoint de diff, petit bug

- app/api_alpha/tests/test_buildings.py
- app/api_alpha/views.py
> Bug sur API de maj de Building

- app/api_alpha/tests/test_buildings.py
- app/api_alpha/views.py
C'est très facile d'en créer visiblement :)
https://sentry.incubateur.net/organizations/betagouv/issues/144010/?project=148&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=5
> Encore une N+1 sur notre API

- app/api_alpha/apps.py
- app/api_alpha/utils/rnb_doc.py
- app/api_alpha/views.py
Notre doc sur Gitbook est particulièrement affreuse en ce moment.
J'ai l'impression que ça bouge côté gitbook.
Avec cette PR j'arrive à faire quelque chose de sympa.
Avant :
Après :
> Ménage OpenAPI

- app/api_alpha/views.py
> Typo formattage openapi

- .github/workflows/deploy_production.yml
- .github/workflows/deploy_staging.yml
Proposition pour rajouter un workflow de déploiement déclenchable manuellement pour déployer staging et ne pas le faire manuellement
Pour tester j'ai l'impression qu'il faut merge dans main ? C.f. https://docs.github.com/fr/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch
> Ajouter un déploiement vers staging

- .github/workflows/deploy_staging.yml
J'avais fait quelques erreurs dans ma PR précédente : 
- `ref` au lieu de `ref_name`
- typo dans la référence `${{ var }}`
- Simple `reset`, alors que dans le cas où on est sur une autre branche on veut changer de branche
Je n'avais pas pensé à forcer un trigger `push` le temps de tester. C'est maintenant chose faite.
> Résoudre deploy_staging

- app/batid/services/guess_bdg_new.py
- app/batid/tests/test_guess.py
- app/batid/utils/misc.py
- app/poetry.lock
- app/pyproject.toml
Le diff est assez gros, mais c'est surtout dû à du refactoring de ["nested condition to guard clause"](https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html).
Les "vrais" changements sont (voir commits par commits si mieux ?) :
- tqdm pour afficher du progrès à la place de logs, pour l'esthétisme mais aussi dans l'optique d'avoir le throughput par batch affiché "gratuitement" et pouvoir comparer avec les évolutions
- Rebasculer sur le logique "closest from point" une fois un géocoding par nom trouvé
- Prendre l'adresse avec le plus haut score en cas de plusieurs retours de la BAN
> Guesser improvements for Ramses

- app/app/settings.py
- app/batid/middlewares.py
> Add logging in production

- app/batid/services/data_gouv_publication.py
- app/batid/tests/test_data_gouv_publication.py
Suite à une demande de la MACIF et à d'autres demandes antérieures.
> Ajout des parcelles à la publication data.gouv

- app/api_alpha/permissions.py
- app/api_alpha/serializers.py
- app/api_alpha/tests/test_auth.py
- app/app/settings.py
Dès qu'un user créé son compte il fait partie du groupe "Contributors".
Ca va aussi nous être utile pour récupérer des tokens staging.
> Creation de token automatique et rattachement au groupe Contributors

- app/batid/management/commands/create_tokens.py
J'ai eu à créer des tokens en utilisant l'outil fait par Bastien. C'était la première fois que je le prenais en main et j'ai senti que je manquais un peu de maitrise sur ce qui allait être produit.
J'ai ajouté une visualisation des utilisateurs qui vont être créé et un message de confirmation avant création
> Amélioration de la commande de création de tokens pour les ADS

- app/batid/services/data_gouv_publication.py
Suite à https://github.com/fab-geocommuns/RNB-coeur/pull/606, on a plus de détails sur l'erreur, c'est un timeout de la transaction pour l'export national.
Sur notre serveur de prod, le timeout d'une transaction est fixée à 1 jour (`SHOW statement_timeout;`).
Or les derniers exports nationaux pré-ajout du cadastre prenaient entre 21H et 24H, donc on était ricrac sans le savoir.
L'ajout du cadastre prend environ 30% de temps en plus, donc je set pour cette transaction en particulier un timeout à 48H, on va voir ce que ça donne ! 🤞
> Réparer export data.gouv national

- app/api_alpha/tests/test_summerchallenge_api.py
- app/api_alpha/views.py
On a besoin d'envoyer au front les infos de score d'un utilisateur même si celui n'est pas encore dans le classement. Jusqu'à maintenant on envoyait une 404
> Score et classement pour primo participant

- common-services.yml
C.f. https://github.com/nginx-proxy/nginx-proxy/blob/db0be23b70b2859ac4db2edb71970ab63d2e4d92/docs/README.md?plain=1#L799
> Fix nginx boot warning

- app/batid/services/closest_bdg.py
- app/batid/services/guess_bdg_new.py
- app/poetry.lock
- app/pyproject.toml
- Revert la version de Notebook pour pouvoir le lancer (réapparition de https://www.notion.so/referentielnationaldesbatiments/6a9fae4f460d4417b8810461fb1a49ef?v=e901e0bf649e4994af6375f404d762d2&p=4952ea3eebcb471ba4b55e57d7a2a9cf&pm=s suite à une update)
- Utiliser un ContextManager pour les connexions dans le guesser. J'ai eu pas mal de soucis de connexions restées ouvertes soudainement.
- Caster en geography dans `get_closest_from_poly` pour utiliser l'index
- Paramétrer `PartialRoofHandler` pour pouvoir l'utiliser pour du matching plus général à partir de formes
> Changements communs aux rapprochements
